[package]
name = "upsee"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
image = "0.25"
nokhwa = { version = "0.10.10", features = ["input-native"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tract-onnx = "0.22.0"
